version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: ml_nids_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nids_logs
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafanapass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  grafana:
    image: grafana/grafana
    container_name: ml_nids_grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin

volumes:
  mysql_data:
  grafana_data:
